import java.util.*;
public class Database {
    private ArrayList<TR> database = new ArrayList<>();
    private Random gen = new Random();
    public Database() {
        TR tr0 = new TR(0," Swords Dance    ","Normal");
        database.add(tr0);
        TR tr1 = new TR(1," Body Slam       ","Normal");
        database.add(tr1);
        TR tr2 = new TR(2," Flamethrower    ","Fire");
        database.add(tr2);
        TR tr3 = new TR(3," Hydro Pump      ","Water");
        database.add(tr3);
        TR tr4 = new TR(4," Water Pulse     ","Water");
        database.add(tr4);
        TR tr5 = new TR(5," Ice Beam        ","Ice");
        database.add(tr5);
        TR tr6 = new TR(6," Blizzard        ","Ice");
        database.add(tr6);
        TR tr7 = new TR(7," Low Kick        ","Fighting");
        database.add(tr7);
        TR tr8 = new TR(8," Thunderbolt     ","Electric");
        database.add(tr8);
        TR tr9 = new TR(9," Thunder         ","Electric");
        database.add(tr9);
        TR tr10 = new TR(10," Earthquake      ","Ground");
        database.add(tr10);
        TR tr11 = new TR(11," Psychic         ","Psychic");
        database.add(tr11);
        TR tr12 = new TR(12," Agility         ","Psychic");
        database.add(tr12);
        TR tr13 = new TR(13," Fosus Energy    ","Normal");
        database.add(tr13);
        TR tr14 = new TR(14," Metronome       ","Normal");
        database.add(tr14);
        TR tr15 = new TR(15," Fire Blast      ","Fire");
        database.add(tr15);
        TR tr16 = new TR(16," Aqua Tail       ","Water");
        database.add(tr16);
        TR tr17 = new TR(17," Amnesia         ","Psychic");
        database.add(tr17);
        TR tr18 = new TR(18," Leech Life      ","Bug");
        database.add(tr18);
        TR tr19 = new TR(19," Tri Attack      ","Normal");
        database.add(tr19);
        TR tr20 = new TR(20," Substitute      ","Normal");
        database.add(tr20);
        TR tr21 = new TR(21," Reversal        ","Fighting");
        database.add(tr21);
        TR tr22 = new TR(22," Sludge Bomb     ","Poison");
        database.add(tr22);
        TR tr23 = new TR(23," Spikes          ","Ground");
        database.add(tr23);
        TR tr24 = new TR(24," Outrage         ","Dragon");
        database.add(tr24);
        TR tr25 = new TR(25," Psyshock        ","Psychic");
        database.add(tr25);
        TR tr26 = new TR(26," Endure          ","Normal");
        database.add(tr26);
        TR tr27 = new TR(27," Sleep Talk      ","Normal");
        database.add(tr27);
        TR tr28 = new TR(28," Megahorn        ","Bug");
        database.add(tr28);
        TR tr29 = new TR(29," Baton Pass      ","Normal");
        database.add(tr29);
        TR tr30 = new TR(30," Encore          ","Normal");
        database.add(tr30);
        TR tr31 = new TR(31," Iron Tail       ","Steel");
        database.add(tr31);
        TR tr32 = new TR(32," Crunch          ","Dark");
        database.add(tr32);
        TR tr33 = new TR(33," Shadow Ball     ","Ghost");
        database.add(tr33);
        TR tr34 = new TR(34," Future Sight    ","Psychic");
        database.add(tr34);
        TR tr35 = new TR(35," Uproar          ","Normal");
        database.add(tr35);
        TR tr36 = new TR(36," Heat Wave       ","Fire");
        database.add(tr36);
        TR tr37 = new TR(37," Taunt           ","Dark");
        database.add(tr37);
        TR tr38 = new TR(38," Trick           ","Psychic");
        database.add(tr38);
        TR tr39 = new TR(39," Superpower      ","Fighting");
        database.add(tr39);
        TR tr40 = new TR(40," Skill Swap      ","Psychic");
        database.add(tr40);
        TR tr41 = new TR(41," Blaze Kick      ","Fire");
        database.add(tr41);
        TR tr42 = new TR(42," Hyper Voice     ","Normal");
        database.add(tr42);
        TR tr43 = new TR(43," Overheat        ","Fire");
        database.add(tr43);
        TR tr44 = new TR(44," Cosmic Power    ","Psychic");
        database.add(tr44);
        TR tr45 = new TR(45," Muddy Water     ","Water");
        database.add(tr45);
        TR tr46 = new TR(46," Iron Defense    ","Steel");
        database.add(tr46);
        TR tr47 = new TR(47," Dragon Claw     ","Dragon");
        database.add(tr47);
        TR tr48 = new TR(48," Bulk Up         ","Fighting");
        database.add(tr48);
        TR tr49 = new TR(49," Calm Mind       ","Psychic");
        database.add(tr49);
        TR tr50 = new TR(50," Leaf Blade     ","Grass");
        database.add(tr50);
        TR tr51 = new TR(51," Dragon Dance    ","Dragon");
        database.add(tr51);
        TR tr52 = new TR(52," Gyro Ball       ","Steel");
        database.add(tr52);
        TR tr53 = new TR(53," Close Combat    ","Fighting");
        database.add(tr53);
        TR tr54 = new TR(54," Toxic Spikes    ","Poison");
        database.add(tr54);
        TR tr55 = new TR(55," Flare Blitz     ","Fire");
        database.add(tr55);
        TR tr56 = new TR(56," Aura Sphere     ","Fighting");
        database.add(tr56);
        TR tr57 = new TR(57," Poison Jab      ","Poison");
        database.add(tr57);
        TR tr58 = new TR(58," Dark Pulse      ","Dark");
        database.add(tr58);
        TR tr59 = new TR(59," Seed Bomb       ","Grass");
        database.add(tr59);
        TR tr60 = new TR(60," X-Scissor       ","Bug");
        database.add(tr60);
        TR tr61 = new TR(61," Bug Buzz        ","Bug");
        database.add(tr61);
        TR tr62 = new TR(62," Dragon Pulse    ","Dragon");
        database.add(tr62);
        TR tr63 = new TR(63," Power Gem       ","Rock");
        database.add(tr63);
        TR tr64 = new TR(64," Focus Blast     ","Fighting");
        database.add(tr64);
        TR tr65 = new TR(65," Energy Ball     ","Grass");
        database.add(tr65);
        TR tr66 = new TR(66," Brave Bird      ","Flying");
        database.add(tr66);
        TR tr67 = new TR(67," Earth Power     ","Ground");
        database.add(tr67);
        TR tr68 = new TR(68," Nasty Plot      ","Dark");
        database.add(tr68);
        TR tr69 = new TR(69," Zen Headbutt    ","Psychic");
        database.add(tr69);
        TR tr70 = new TR(70," Flash Cannon    ","Steel");
        database.add(tr70);
        TR tr71 = new TR(71," Leaf Storm      ","Grass");
        database.add(tr71);
        TR tr72 = new TR(72," Power Whip      ","Grass");
        database.add(tr72);
        TR tr73 = new TR(73," Gunk Shot       ","Poison");
        database.add(tr73);
        TR tr74 = new TR(74," Iron Head       ","Steel");
        database.add(tr74);
        TR tr75 = new TR(75," Stone Edge      ","Rock");
        database.add(tr75);
        TR tr76 = new TR(76," Stealth Rock    ","Rock");
        database.add(tr76);
        TR tr77 = new TR(77," Grass Knot      ","Grass");
        database.add(tr77);
        TR tr78 = new TR(78," Sludge Wave     ","Poison");
        database.add(tr78);
        TR tr79 = new TR(79," Heavy Slam      ","Steel");
        database.add(tr79);
        TR tr80 = new TR(80," Electro Ball    ","Electric");
        database.add(tr80);
        TR tr81 = new TR(81," Foul Play       ","Dark");
        database.add(tr81);
        TR tr82 = new TR(82," Stored Power    ","Psychic");
        database.add(tr82);
        TR tr83 = new TR(83," Ally Switch     ","Psychic");
        database.add(tr83);
        TR tr84 = new TR(84," Scald           ","Water");
        database.add(tr84);
        TR tr85 = new TR(85," Work Up         ","Normal");
        database.add(tr85);
        TR tr86 = new TR(86," Wild Charge     ","Electric");
        database.add(tr86);
        TR tr87 = new TR(87," Drill Run       ","Ground");
        database.add(tr87);
        TR tr88 = new TR(88," Heat Crash      ","Fire");
        database.add(tr88);
        TR tr89 = new TR(89," Hurricane       ","Flying");
        database.add(tr89);
        TR tr90 = new TR(80," Play Rough      ","Fairy");
        database.add(tr90);
        TR tr91 = new TR(91," Venom Drench    ","Poison");
        database.add(tr91);
        TR tr92 = new TR(92," Dazzling Gleam  ","Fairy");
        database.add(tr92);
        TR tr93 = new TR(93," Darkest Lariat  ","Dark");
        database.add(tr93);
        TR tr94 = new TR(94," High Horsepower ","Ground");
        database.add(tr94);
        TR tr95 = new TR(95," Throat Chop     ","Dark");
        database.add(tr95);
        TR tr96 = new TR(96," Pollen Puff     ","Bug");
        database.add(tr96);
        TR tr97 = new TR(97," Psychic Fangs   ","Psychic");
        database.add(tr97);
        TR tr98 = new TR(98," Liquidation     ","Water");
        database.add(tr98);
        TR tr99 = new TR(99," Body Press      ","Fighting");
        database.add(tr99);
    }
    public TR getTR() {
        int num = gen.nextInt(database.size());
        return database.get(num);
    }
    public TR getByType(String type) {
        TR tr = getTR();
        if (tr.getType().equalsIgnoreCase(type)) {
            return tr;
        }
        return getByType(type);
    }
}